# Generated by Django 3.2.6 on 2021-08-02 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('HUF', 'Hungarian Forint'), ('USD', 'American Dollar')], default='HUF', max_length=3)),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
    ]
