# Generated by Django 3.2.6 on 2021-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spending',
            name='currency',
            field=models.CharField(choices=[('HUF', 'Hungarian Forint'), ('USD', 'American Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
