# Generated by Django 3.2.6 on 2021-08-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0002_auto_20210804_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='currency',
            field=models.CharField(choices=[('HUF', 'Hungarian Forint'), ('USD', 'American Dollar')], max_length=3),
        ),
    ]
