# Generated by Django 3.2.6 on 2021-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0003_alter_spending_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='spending',
            old_name='amount',
            new_name='amount_in_cents',
        ),
    ]
