# Generated by Django 3.2.6 on 2021-08-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0004_auto_20210804_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='amount_in_cents',
            new_name='amount',
        ),
    ]
