# Generated by Django 3.2.6 on 2021-08-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0005_rename_amount_in_cents_spending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='amount_in_usd',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
