# Generated by Django 3.2.6 on 2021-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings_app', '0006_spending_amount_in_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='amount_in_usd',
        ),
        migrations.AddField(
            model_name='spending',
            name='amount_in_huf',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
